server:
  port: 2323
  servlet:
    context-path: /information



spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/airport
  thymeleaf:
    prefix: classpath:/static/
  mvc:
    view:
      prefix: /
      suffix: .html